### ISSUE TITLE
typo in zenodo doc module

### ISSUE THREAD

**Issue by MariellaCC** [DHARPA-Project/kiara_plugin.onboarding#1]
Hi,
I just noticed a typo in the `download.file_bundle.from.zenodo` documentation text: the doc mentions github instead of zenodo.
Should I modify it via a PR or is it easier if you do it directly?
Thanks

**Comment by makkus** [comment]
PR is fine if you have the time, otherwise I can do it myself later as well.

**Comment by MariellaCC** [comment]
Thanks, that's fine, I will do it
